### PR TITLE
Added the ability to set IgnoredError

### PR DESCRIPTION
**Pull request by podzyuban**
This is relevant if you need to write more than 15 number  characters to cell

### CODE REVIEW

**Comment by salvois** [comment]
Hi @podzyuban , sorry for the very late reply.

Thanks for your contribution. I had a look at the modified code and, in my understanding, what it does is adding the ability to suppress the "Number stored as text" little warning that appears, for example, when you write something like '123 (that is, preceding a number with an apostrophe) in a cell.

Thus, this would be not only for big numbers but for any number stored as text in general. I can think about some use cases for it (product codes, maybe with leading zeroes, come to mind), but it's not clear to me why you may want to suppress the warning.

Could you elaborate please?

I'm a little worried about introducing a new potentially memory-intensive feature into the library.
Thanks,
   Salvo

**Comment by podzyuban** [comment]
Hi @salvois!
thanks for the answer!
Thank you very much for your library, it is a great and useful work!

we output large numbers to Excel and have a warning (https://learn.microsoft.com/en-us/office/troubleshoot/excel/long-numbers-incorrectly-in-excel).

Our Excel consists of many lines with large numbers.

We think this is not user friendly and would like to avoid displaying a warning.

I think that such a capability at the XML level is practically cost-free but I could be mistaken.

Thanks,
podzyuban

**Comment by podzyuban** [comment]
Hi, @salvois!

we still have a problem )

Our Excel can contain more than MaxRowNumbers in theory.

Is it possible to change the default setting and make it the responsibility of library users?

Thanks,
podzyuban

**Comment by salvois** [comment]
Hello @podzyuban,
this feature may be problematic because, if I'm understanding the code right, it must accumulate in memory every cell you want to turn off those warnings, thus while it may be simple to implement at XML level, it may cause unexpected high memory consumption, that is against the spirit of this library.

To be honest, I have already included a couple of such features, such as merged cells and shared strings, but I expect both to be used sparingly in a worksheet, and have a broader usefulness than warning suppression. I'm picturing that, in my example of large numbers representing product codes, you could end up with many thousands of cells to suppress warning into.

Thus, while I'm grateful for your suggestion and contribution, I'm afraid I could not include this library.

Concerning your second question, about producing more than 1M rows, I'm afraid that could lead to unexpected results. Major applications such as Excel and LibreOffice do impose that limit, so one could regard LargeXlsx as buggy if that was allowed.
For the record, I had that requirement too, and had to find workarounds such as splitting in multiple worksheets or files, or rearranging the worksheet, because my users could not read the file if I didn't.
On the other hand, if one is producing an XLSX file as a mere interchange format, and there is not interest in opening it with major applications, I feel like there are better file format option such as CSV or newline-delimited JSON (a.k.a. JSON-line) files.

Thanks,
   Salvo

**Comment by podzyuban** [comment]
Hello @salvois 
Maybe then we’ll add the ability to set errors to be ignored only for 1 range. in my example I set this to all data 1 time - I don't set this for every cell and don't see the point in doing so.

**Comment by salvois** [comment]
Hi @podzyuban , 
since, unfortunately, this feature may not be a perfect fit for this library, I'm closing this pull request.
Thank you very much for your proposal.
   Salvo

**Pull request closed without merging**
